use crate::{activity::load_activity, config::AppConfig, storage::Note};
use chrono::{Duration, Local};
use std::{collections::HashMap, fs, io, path::PathBuf};

pub fn save_report(config: &AppConfig, notes: &[Note], days: i64) -> io::Result<PathBuf> {
    let root = config
        .vault_path
        .as_ref()
        .ok_or_else(|| io::Error::other("není vybraný vault"))?;
    let now = Local::now();
    let since = (now - Duration::days(days)).timestamp_millis();
    let entries = load_activity(config)
        .into_iter()
        .filter(|entry| entry.timestamp >= since)
        .collect::<Vec<_>>();
    let label = if days <= 7 { "Weekly" } else { "Monthly" };
    let kind = if days <= 7 { "weekly" } else { "monthly" };
    let total_ms = entries.iter().map(|entry| entry.duration_ms).sum::<u64>();
    let average_ms = total_ms.checked_div(entries.len() as u64).unwrap_or(0);
    let mut note_totals: HashMap<String, (u64, usize)> = HashMap::new();
    for entry in &entries {
        let total = note_totals.entry(entry.note_name.clone()).or_default();
        total.0 = total.0.saturating_add(entry.duration_ms);
        total.1 += 1;
    }
    let mut sorted_notes = note_totals.into_iter().collect::<Vec<_>>();
    sorted_notes.sort_by_key(|(_, (duration, _))| std::cmp::Reverse(*duration));
    let estimated = notes
        .iter()
        .filter(|note| note.time_estimate_minutes.is_some())
        .count();
    let met_estimate = notes
        .iter()
        .filter(|note| {
            note.time_estimate_minutes
                .is_some_and(|minutes| note.duration_ms <= minutes.saturating_mul(60_000))
        })
        .count();

    let mut markdown = format!(
        "# {label} Report — {}\n\n_Generated: {}_\n\n## Overview\n\n- **Period:** last {days} days\n- **Total time:** {}\n- **Total entries:** {}\n- **Average per entry:** {}\n- **Daily goal:** {}\n\n",
        config.nick.as_deref().unwrap_or("mmStopWatch"),
        now.format("%Y-%m-%d %H:%M:%S"),
        format_duration(total_ms),
        entries.len(),
        format_duration(average_ms),
        format_duration(config.daily_goal_ms),
    );
    markdown.push_str("## Top Notes\n\n| Note | Total | Sessions |\n| :--- | :--- | :--- |\n");
    for (name, (duration, count)) in sorted_notes.into_iter().take(15) {
        markdown.push_str(&format!(
            "| {} | {} | {} |\n",
            name.replace('|', "\\|"),
            format_duration(duration),
            count
        ));
    }
    if estimated > 0 {
        markdown.push_str(&format!(
            "\n## Estimate Accuracy\n\n- **Sessions with estimates:** {estimated}\n- **Met estimates:** {met_estimate}\n- **Accuracy:** {}%\n",
            met_estimate.saturating_mul(100).checked_div(estimated).unwrap_or(0)
        ));
    }
    markdown.push_str("\n---\n\n_Report generated by mmStopWatch_\n");

    let path = root.join(format!("mmST-{kind}-report-{}.md", now.format("%Y-%m-%d")));
    let temporary = path.with_extension("md.tmp");
    fs::write(&temporary, markdown)?;
    #[cfg(target_os = "windows")]
    if path.exists() {
        fs::copy(&temporary, &path)?;
        fs::remove_file(temporary)?;
        return Ok(path);
    }
    fs::rename(temporary, &path)?;
    Ok(path)
}

fn format_duration(milliseconds: u64) -> String {
    let seconds = milliseconds / 1_000;
    format!(
        "{}h {}m {}s",
        seconds / 3_600,
        seconds / 60 % 60,
        seconds % 60
    )
}
