import { createServer } from 'node:http'
import { TextDecoder } from 'node:util'
import { createService, safeError } from './service.mjs'
import { routes, validateSchema, timerMutationSchema, noteDurationSchema, noteGetSchema } from './schema.mjs'
const MAX_BODY = 1024 * 1024
const send = (res, status, body) => { res.writeHead(status, { 'content-type': 'application/json; charset=utf-8', 'cache-control': 'no-store' }); res.end(JSON.stringify(body)) }
const readBody = req => new Promise((resolve, reject) => { let data = Buffer.alloc(0); let settled = false; const decoder = new TextDecoder('utf-8', { fatal: true }); const rejectOnce = error => { if (settled) return; settled = true; reject(error) }; req.on('data', chunk => { if (settled) return; data = Buffer.concat([data, chunk]); if (data.length > MAX_BODY) { rejectOnce(Object.assign(new Error('Request body exceeds 1 MiB'), { status: 413 })); req.resume() } }); req.on('end', () => { if (settled) return; settled = true; try { resolve(data.length ? JSON.parse(decoder.decode(data)) : {}) } catch { reject(new Error('Malformed JSON body')) } }); req.on('error', rejectOnce) })
export function createHttpServer({ service = createService(), token = process.env.MMSTOPWATCH_CONTROL_PLANE_TOKEN, host = '127.0.0.1', port = Number(process.env.MMSTOPWATCH_HTTP_PORT ?? 9376), origins = (process.env.MMSTOPWATCH_ALLOWED_ORIGINS ?? '').split(',').map(value => value.trim()).filter(Boolean) } = {}) {
  if (host !== '127.0.0.1' || typeof token !== 'string' || !token) throw new Error('HTTP requires loopback host and non-empty token')
  const server = createServer(async (req, res) => { let url; try { url = new URL(req.url, `http://${host}`) } catch { return send(res, 400, safeError('MALFORMED_REQUEST', 'Invalid URL')) }; const origin = req.headers.origin; if (origin && !origins.includes(origin)) return send(res, 403, safeError('ORIGIN_DENIED', 'Origin is not allowed')); if (url.pathname === '/healthz') return req.method === 'GET' ? send(res, 200, { ok: true, data: { ready: true } }) : send(res, 405, safeError('METHOD_NOT_ALLOWED', 'Method is not allowed')); if (req.headers.authorization !== `Bearer ${token}`) return send(res, 401, safeError('AUTH_REQUIRED', 'Bearer token is required'))
    const methodMap = { '/api/v1/status': ['GET', 'status'], '/api/v1/capabilities': ['GET', 'capabilities'], '/api/v1/timers': ['GET', 'timersList'], '/api/v1/notes': ['GET', 'notesList'], '/api/v1/notes/get': ['GET', 'notesGet'], '/api/v1/profiles': ['GET', 'profiles'], '/api/v1/config': ['GET', 'config'], '/api/v1/notifications': ['GET', 'notifications'], '/api/v1/stats': ['GET', 'stats'], '/api/v1/reports/preview': ['GET', 'reportPreview'], '/api/v1/timers/mutate': ['POST', 'timersMutate'], '/api/v1/notes/update-duration': ['POST', 'updateDuration'] }; const route = methodMap[url.pathname]; if (!route || !routes.includes(url.pathname)) return send(res, 404, safeError('NOT_FOUND', 'Route not found')); if (req.method !== route[0]) return send(res, 405, safeError('METHOD_NOT_ALLOWED', 'Method is not allowed'))
    let body = {}; try { if (req.method === 'POST') body = await readBody(req) } catch (error) { return send(res, error.status ?? 400, safeError(error.status === 413 ? 'BODY_TOO_LARGE' : 'MALFORMED_REQUEST', error.message)) }; if (route[1] === 'notesGet' && [...url.searchParams.keys()].some(key => key !== 'path')) return send(res, 400, safeError('INVALID_ARGUMENT', 'Request arguments do not match the declared schema')); const input = route[1] === 'notesGet' ? { path: url.searchParams.get('path') } : body; const schema = route[1] === 'notesGet' ? noteGetSchema : route[1] === 'timersMutate' ? timerMutationSchema : route[1] === 'updateDuration' ? noteDurationSchema : null; if (schema && !validateSchema(input, schema)) return send(res, 400, safeError('INVALID_ARGUMENT', 'Request arguments do not match the declared schema')); try { const result = route[1] === 'notesGet' ? await service.notesGet(input.path) : route[1] === 'timersMutate' || route[1] === 'updateDuration' ? await service[route[1]](body) : await service[route[1]](); return send(res, result.ok ? 200 : 409, result) } catch { return send(res, 500, safeError('INTERNAL_ERROR', 'Request failed safely')) }
  }); server.requestTimeout = 5000; server.headersTimeout = 6000; server.maxHeadersCount = 64; return server
}
if (import.meta.url === `file://${process.argv[1]}`) { const server = createHttpServer(); server.listen(Number(process.env.MMSTOPWATCH_HTTP_PORT ?? 9376), '127.0.0.1', () => process.stderr.write('mmStopWatch MCP HTTP listening on loopback\n')); const close = () => server.close(() => process.exit(0)); process.once('SIGINT', close); process.once('SIGTERM', close) }
