import { access, lstat, mkdir, readdir, readFile, rename, rm, stat, unlink, writeFile, realpath } from 'node:fs/promises'
import { realpathSync } from 'node:fs'
import { createHash, randomUUID } from 'node:crypto'
import { isAbsolute, join, normalize, relative, sep } from 'node:path'

export const MAX_FILE_BYTES = 1024 * 1024
const LOCK_WAIT_MS = 5000
const STALE_LOCK_MS = 30000
const hidden = new Set(['.obsidian', '.git'])
const object = value => value && typeof value === 'object' && !Array.isArray(value)
const hash = value => createHash('sha256').update(value).digest('hex')
const json = value => JSON.stringify(value)
const ok = (data, revision) => ({ ok: true, data, ...(revision ? { revision } : {}) })
export const safeError = (code, message, details = {}) => ({ ok: false, error: { code, message, ...details } })
const formatDuration = ms => `${String(Math.floor(ms / 3600000)).padStart(2, '0')}:${String(Math.floor(ms / 60000) % 60).padStart(2, '0')}:${String(Math.floor(ms / 1000) % 60).padStart(2, '0')}`
const boundedRead = async path => { const data = await readFile(path); if (data.length > MAX_FILE_BYTES) throw new Error('File exceeds limit'); return data.toString('utf8') }
const parseValue = raw => { const value = raw.trim(); if (value.startsWith('[') && value.endsWith(']')) return value.slice(1, -1).split(',').map(v => v.trim().replace(/^['"]|['"]$/g, '')).filter(Boolean); if (/^(true|false)$/.test(value)) return value === 'true'; if (/^-?\d+(\.\d+)?$/.test(value)) return Number(value); return value.replace(/^['"]|['"]$/g, '') }
const frontmatterBlock = text => { if (!text.startsWith('---')) return null; const contentStart = text.indexOf('\n') + 1; if (contentStart === 0) return null; const delimiterStart = text.indexOf('\n---', contentStart); if (delimiterStart < 0) return null; const contentEnd = delimiterStart > contentStart && text[delimiterStart - 1] === '\r' ? delimiterStart - 1 : delimiterStart; return { contentStart, contentEnd, content: text.slice(contentStart, contentEnd), lineEnding: text.slice(contentEnd, delimiterStart + 1) } }
const frontmatter = text => { const block = frontmatterBlock(text); if (!block) return {}; const result = {}; for (const line of block.content.split(/\r?\n/)) { const match = line.match(/^([A-Za-z][\w-]{0,63}):\s*(.*)$/); if (match) result[match[1]] = parseValue(match[2]) } return result }
async function atomicReplace(path, content, beforeReplace = async () => {}) { const temp = `${path}.${randomUUID()}.tmp`; try { await writeFile(temp, content, { mode: 0o600 }); await beforeReplace(); await rename(temp, path) } finally { await unlink(temp).catch(() => {}) } }

export function createService({ vaultPath = process.env.MMSTOPWATCH_VAULT_PATH, profile = process.env.MMSTOPWATCH_PROFILE ?? 'default' } = {}) {
  if (!vaultPath || !isAbsolute(vaultPath) || !/^[A-Za-z0-9_-]{1,32}$/.test(profile)) throw new Error('Absolute vault path and safe profile are required')
  const root = normalize(realpathSync(vaultPath)); const profileDir = join(root, `.mmST-${profile}`); const configPath = join(profileDir, 'config.json'); const timerPath = join(profileDir, 'mcp-timers.json'); const activityPath = join(profileDir, 'activity.json'); const lockPath = join(profileDir, 'mcp-mutations.lock'); const ownerPath = join(lockPath, 'owner')
  let mutationTail = Promise.resolve()
  const scopeError = () => { const error = new Error('Profile path is outside or not a directory within the vault'); error.code = 'SCOPE_VIOLATION'; return error }
  const profileBoundary = async ({ create = false } = {}) => {
    let info
    try { info = await lstat(profileDir) } catch (error) {
      if (error.code !== 'ENOENT') throw error
      if (!create) return false
      try { await mkdir(profileDir) } catch (mkdirError) { if (mkdirError.code !== 'EEXIST') throw mkdirError }
      info = await lstat(profileDir)
    }
    if (info.isSymbolicLink() || !info.isDirectory()) throw scopeError()
    const actual = await realpath(profileDir); const rel = relative(root, actual)
    if (rel === '..' || rel.startsWith(`..${sep}`) || isAbsolute(rel)) throw scopeError()
    return actual
  }
  const requireProfileBoundary = async () => { const actual = await profileBoundary(); if (!actual) { const error = new Error('Vault or selected profile is unavailable'); error.code = 'NOT_CONFIGURED'; throw error }; return actual }
  const isWithin = (base, candidate) => { const rel = relative(base, candidate); return rel === '' || (rel !== '..' && !rel.startsWith(`..${sep}`) && !isAbsolute(rel)) }
  const profileFileBoundary = async (path, { create = false } = {}) => { const actualProfile = await profileBoundary({ create }); if (!actualProfile) return false; if (!isWithin(actualProfile, normalize(path))) throw scopeError(); let info; try { info = await lstat(path) } catch (error) { if (error.code === 'ENOENT') return false; throw error }; if (info.isSymbolicLink() || !info.isFile()) throw scopeError(); const actual = await realpath(path); if (!isWithin(actualProfile, actual) || !(await stat(actual)).isFile()) throw scopeError(); return actual }
  const replaceProfileFile = async (path, content) => { await profileFileBoundary(path, { create: true }); await atomicReplace(path, content, async () => { await profileFileBoundary(path, { create: true }) }) }
  const readError = (error, fallbackCode = 'READ_FAILED') => { const scopeViolation = error.code === 'SCOPE_VIOLATION' || error.message === 'Path is outside vault'; const code = scopeViolation ? 'SCOPE_VIOLATION' : error.code === 'NOT_CONFIGURED' ? 'NOT_CONFIGURED' : fallbackCode; const message = code === 'SCOPE_VIOLATION' ? 'Selected profile is outside the vault' : code === 'NOT_CONFIGURED' ? 'Vault or selected profile is unavailable' : error.message; return safeError(code, message) }
  const lockIsStale = async () => { let info; try { info = await stat(lockPath) } catch { return false }; if (Date.now() - info.mtimeMs < STALE_LOCK_MS) return false; let owner; try { owner = JSON.parse(await readFile(ownerPath, 'utf8')) } catch (error) { return error.code === 'ENOENT' || error instanceof SyntaxError }; if (!Number.isInteger(owner.pid) || typeof owner.token !== 'string' || !Number.isFinite(owner.createdAt)) return true; try { process.kill(owner.pid, 0); return false } catch (error) { return error.code === 'ESRCH' } }
  const acquireLock = async () => { await profileBoundary({ create: true }); const started = Date.now(); const token = randomUUID(); while (Date.now() - started < LOCK_WAIT_MS) { try { await mkdir(lockPath); try { await writeFile(ownerPath, JSON.stringify({ pid: process.pid, token, createdAt: Date.now() }), { flag: 'wx', mode: 0o600 }) } catch (error) { await rm(lockPath, { recursive: true, force: true }); throw error }; return async () => { try { const owner = JSON.parse(await readFile(ownerPath, 'utf8')); if (owner.token === token && owner.pid === process.pid) await rm(lockPath, { recursive: true, force: true }) } catch {} } } catch (error) { if (error.code !== 'EEXIST') throw error; if (await lockIsStale()) await rm(lockPath, { recursive: true, force: true }); await new Promise(resolve => setTimeout(resolve, 25)) } } throw new Error('Mutation lock timed out') }
  const withMutationLock = callback => { const run = mutationTail.then(async () => { const release = await acquireLock(); try { return await callback() } finally { await release() } }); mutationTail = run.catch(() => {}); return run }
  const loadConfig = async () => { await requireProfileBoundary(); const file = await profileFileBoundary(configPath); if (!file) return { nick: profile, frontmatterKey: 'Timework', timeEstimateKey: 'timeEstimate', dailyGoalMs: 0 }; try { const parsed = JSON.parse(await boundedRead(file)); return { nick: parsed.nick, frontmatterKey: parsed.frontmatterKey ?? 'Timework', timeEstimateKey: parsed.timeEstimateKey ?? 'timeEstimate', dailyGoalMs: Number(parsed.dailyGoalMs) || 0 } } catch { return { nick: profile, frontmatterKey: 'Timework', timeEstimateKey: 'timeEstimate', dailyGoalMs: 0 } } }
  const boundedPath = async candidate => { if (typeof candidate !== 'string' || !candidate || candidate.includes('\0')) throw new Error('Invalid path'); const lexical = normalize(isAbsolute(candidate) ? candidate : join(root, candidate)); const rel = relative(root, lexical); if (rel === '..' || rel.startsWith(`..${sep}`) || isAbsolute(rel)) throw new Error('Path is outside vault'); const actual = await realpath(lexical); const actualRel = relative(root, actual); if (actualRel === '..' || actualRel.startsWith(`..${sep}`) || isAbsolute(actualRel)) throw new Error('Path is outside vault'); return actual }
  const files = async (dir = root) => { const result = []; for (const entry of await readdir(dir, { withFileTypes: true })) { if (entry.name.startsWith('.') || hidden.has(entry.name) || entry.name.startsWith('.mmST-')) continue; const full = join(dir, entry.name); if (entry.isDirectory()) result.push(...await files(full)); else if (entry.isFile() && entry.name.endsWith('.md')) { try { await boundedPath(relative(root, full)); result.push(full) } catch {} } } return result.sort() }
  const loadTimers = async () => { await requireProfileBoundary(); const file = await profileFileBoundary(timerPath); if (!file) return []; try { const value = JSON.parse(await boundedRead(file)); return Array.isArray(value) ? value : [] } catch { return [] } }
  const revisionOf = value => hash(json(Array.isArray(value) ? value.map(({ lastResult, ...timer }) => timer) : value)); const saveTimers = async value => { await replaceProfileFile(timerPath, json(value)) }
  const noteData = async full => { const text = await boundedRead(full); const config = await loadConfig(); const meta = frontmatter(text); const allow = {}; for (const key of [config.frontmatterKey, config.timeEstimateKey, 'tags', 'title']) if (meta[key] !== undefined) allow[key] = meta[key]; return { text, allow, revision: hash(text) } }
  const readNote = async path => { try { await requireProfileBoundary(); const full = await boundedPath(path); if (!full.endsWith('.md') || full.includes(`${sep}.`)) return safeError('INVALID_PATH', 'Only visible Markdown notes are available'); const note = await noteData(full); return ok({ path: relative(root, full).split(sep).join('/'), frontmatter: note.allow, revision: note.revision }, note.revision) } catch (error) { return readError(error, 'NOT_FOUND') } }
  const readActivity = async () => { await requireProfileBoundary(); const file = await profileFileBoundary(activityPath); if (!file) return { entries: [] }; try { const history = JSON.parse(await boundedRead(file)); return object(history) && Array.isArray(history.entries) ? history : { entries: [] } } catch { return { entries: [] } } }
  const activityResult = async operationId => (await readActivity()).entries.find(item => item.operationId === operationId)?.result
  const activity = async entry => { const history = await readActivity(); if (history.entries.some(item => item.operationId === entry.operationId)) return; history.entries.push(entry); await replaceProfileFile(activityPath, json(history)) }
  const validateDurationMutation = (args = {}) => { const { durationMs: ms, confirmed } = args ?? {}; return confirmed !== true ? safeError('CONFIRMATION_REQUIRED', 'Mutation requires confirmed: true') : !Number.isInteger(ms) || ms < 0 || ms > 2678400000 ? safeError('INVALID_DURATION', 'Duration is outside bounds') : null }
  const validateTimerMutation = (args = {}) => { const { timerId, operation, confirmed, expectedRevision, notePath } = args ?? {}; return confirmed !== true ? safeError('CONFIRMATION_REQUIRED', 'Mutation requires confirmed: true') : !['start', 'pause', 'resume', 'stop'].includes(operation) || typeof expectedRevision !== 'string' || !expectedRevision || (operation === 'start' ? typeof notePath !== 'string' : typeof timerId !== 'string') ? safeError('INVALID_TIMER', 'Timer mutation fields are invalid') : null }
  const updateDurationLocked = async ({ path, durationMs: ms, confirmed, expectedRevision, operationId = randomUUID(), noteName } = {}) => { const validation = validateDurationMutation({ durationMs: ms, confirmed }); if (validation) return validation; const prior = await activityResult(operationId); if (prior) return prior; let full; try { full = await boundedPath(path) } catch { return safeError('SCOPE_VIOLATION', 'Note path is outside the vault') }; let note; try { note = await noteData(full) } catch (error) { return error.code === 'SCOPE_VIOLATION' ? safeError('SCOPE_VIOLATION', 'Selected profile is outside the vault') : safeError('NOT_FOUND', 'Note not found') }; if (note.revision !== expectedRevision) return safeError('STALE_REVISION', 'Note revision is stale'); const config = await loadConfig(); const key = config.frontmatterKey.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'); const match = new RegExp(`^${key}:[^\\r\\n]*`, 'm'); const block = frontmatterBlock(note.text); const durationLine = `${config.frontmatterKey}: ${formatDuration(ms)}`; const updated = block ? (match.test(block.content) ? `${note.text.slice(0, block.contentStart)}${block.content.replace(match, durationLine)}${note.text.slice(block.contentEnd)}` : `${note.text.slice(0, block.contentStart)}${block.content}${block.content && !block.content.endsWith('\n') ? block.lineEnding : ''}${durationLine}${note.text.slice(block.contentEnd)}`) : `---\n${durationLine}\n---\n${note.text}`; try { await atomicReplace(full, updated, async () => { const latest = await noteData(full); if (latest.revision !== expectedRevision) throw new Error('STALE_REVISION') }); const result = ok({ path, durationMs: ms, operationId }, hash(updated)); await activity({ operationId, timestamp: Date.now(), durationMs: ms, notePath: path, noteName: noteName ?? path.split('/').pop().replace(/\.md$/, ''), savedAt: Date.now(), endTimestamp: Date.now(), result }); return result } catch (error) { return safeError(error.message === 'STALE_REVISION' ? 'STALE_REVISION' : 'WRITE_FAILED', error.message === 'STALE_REVISION' ? 'Note revision is stale' : 'Atomic note write failed') } }
  const lockedMutation = callback => withMutationLock(callback).catch(error => error.code === 'SCOPE_VIOLATION' ? safeError('SCOPE_VIOLATION', 'Selected profile is outside the vault') : error.message === 'Mutation lock timed out' ? safeError('LOCK_TIMEOUT', 'Mutation is busy; retry the operation') : safeError('WRITE_FAILED', 'Mutation failed'))
  const updateDuration = args => { const validation = validateDurationMutation(args); return validation ? Promise.resolve(validation) : lockedMutation(() => updateDurationLocked(args)) }
  const timersMutateLocked = async ({ timerId, operation, confirmed, expectedRevision, notePath, operationId = randomUUID() } = {}) => { const validation = validateTimerMutation({ timerId, operation, confirmed, expectedRevision, notePath }); if (validation) return validation; const timers = await loadTimers(); const index = timers.findIndex(timer => timer.id === timerId); const prior = timers.find(timer => timer.lastOperationId === operationId); if (prior?.lastResult) return prior.lastResult; if (expectedRevision !== revisionOf(timers)) return safeError('STALE_REVISION', 'Timer revision is stale'); let timer; if (index < 0 && operation === 'start') { const note = await readNote(notePath); if (!note.ok) return note; timer = { id: timerId ?? randomUUID(), notePath, noteRevision: note.revision, state: 'running', startedAt: Date.now(), accumulatedMs: 0 } } else if (index < 0) return safeError('UNKNOWN_TIMER', 'Timer is not known to the external MCP adapter'); else timer = { ...timers[index] }; const now = Date.now(); const elapsed = timer.state === 'running' ? Math.floor(Math.max(0, now - (timer.startedAt ?? now))) : 0; if (operation === 'pause' || operation === 'stop') { timer.accumulatedMs = Math.max(0, (timer.accumulatedMs ?? 0) + elapsed); timer.durationMs = timer.accumulatedMs; timer.state = operation === 'stop' ? 'stopped' : 'paused' } else { timer.state = 'running'; timer.startedAt = now }; timer.lastOperationId = operationId; if (operation === 'stop' && timer.notePath) { const noteResult = await updateDurationLocked({ path: timer.notePath, durationMs: timer.durationMs, confirmed: true, expectedRevision: timer.noteRevision, operationId: `${operationId}:note` }); if (!noteResult.ok) return noteResult; timer.noteRevision = noteResult.revision } const next = index < 0 ? [...timers, timer] : timers.map((item, itemIndex) => itemIndex === index ? timer : item); await saveTimers(next); const result = ok({ ...timer, operationId }, revisionOf(next)); timer.lastResult = result; await saveTimers(next); return result }
  const timersMutate = args => { const validation = validateTimerMutation(args); return validation ? Promise.resolve(validation) : lockedMutation(() => timersMutateLocked(args)) }
  const noteEntries = async () => { await requireProfileBoundary(); const config = await loadConfig(); const entries = []; for (const full of await files()) { const note = await noteData(full); entries.push({ path: relative(root, full).split(sep).join('/'), title: typeof note.allow.title === 'string' ? note.allow.title : full.split(sep).pop().replace(/\.md$/, ''), frontmatter: note.allow, revision: note.revision }) } return entries }
  return { async status() { try { await access(root); if (!(await profileBoundary())) return safeError('NOT_CONFIGURED', 'Vault or selected profile is unavailable'); return ok({ appVersion: '1.7.5', ready: true, localOnly: true, dataBoundary: 'external-file-backed-mcp', guiState: 'not available', telemetry: false }) } catch (error) { return error.code === 'SCOPE_VIOLATION' ? safeError('SCOPE_VIOLATION', 'Selected profile is outside the vault') : safeError('NOT_CONFIGURED', 'Vault or selected profile is unavailable') } }, async capabilities() { return ok({ protocolVersion: '2025-06-18', commands: ['status', 'capabilities', 'notes.list', 'notes.get', 'timers.list', 'profiles.list', 'config', 'notifications', 'stats', 'reports.preview', 'timers.mutate', 'notes.updateDuration'], unavailable: { noteDelete: 'not implemented', configMutation: 'not implemented', measurement: 'explicitly deferred' } }) }, notesList: async () => { try { return ok(await noteEntries()) } catch (error) { return readError(error) } }, notesGet: readNote, async timersList() { try { const timers = await loadTimers(); return ok(timers.map(({ secret, ...timer }) => timer), revisionOf(timers)) } catch (error) { return readError(error) } }, async profiles() { try { return ok((await readdir(root, { withFileTypes: true })).filter(entry => entry.isDirectory() && entry.name.startsWith('.mmST-')).map(entry => ({ profile: entry.name.slice(6) }))) } catch { return safeError('READ_FAILED', 'Vault is unavailable') } }, async config() { try { return ok({ profile, config: await loadConfig() }) } catch (error) { return readError(error) } }, async notifications() { return ok({ enabled: false, source: 'external-file-backed-adapter' }) }, async stats() { try { const notes = await noteEntries(); return ok({ noteCount: notes.length }) } catch (error) { return readError(error) } }, async reportPreview() { const stats = await this.stats(); return stats.ok ? ok({ summary: stats.data, bounded: true }) : stats }, timersMutate, updateDuration }
}
