import { stdin, stdout, stderr } from 'node:process'
import { TextDecoder } from 'node:util'
import { createService } from './service.mjs'
import { timerMutationSchema, noteDurationSchema, noteGetSchema, validateSchema } from './schema.mjs'
export const PROTOCOL_VERSION = '2025-06-18'
const MAX_FRAME_BYTES = 1024 * 1024; const VERSION = '1.7.5'
const noArgs = { type: 'object', properties: {}, additionalProperties: false }
const tools = [['status', 'Read status', noArgs, 'status'], ['capabilities', 'Read capabilities', noArgs, 'capabilities'], ['notes_list', 'List scoped notes', noArgs, 'notesList'], ['note_get', 'Read allowlisted note metadata', noteGetSchema, 'notesGet'], ['timers_list', 'List external MCP timers', noArgs, 'timersList'], ['profiles_list', 'List profiles', noArgs, 'profiles'], ['config', 'Read redacted config metadata', noArgs, 'config'], ['notifications', 'Read notification status', noArgs, 'notifications'], ['stats', 'Read bounded statistics', noArgs, 'stats'], ['report_preview', 'Read bounded report preview', noArgs, 'reportPreview'], ['timer_mutate', 'Confirmation-gated timer mutation', timerMutationSchema, 'timersMutate'], ['note_update_duration', 'Confirmation-gated Timework duration update', noteDurationSchema, 'updateDuration']].map(([suffix, description, inputSchema, method]) => ({ name: `mmstopwatch_${suffix}`, description, inputSchema, method }))
const isObject = value => value !== null && typeof value === 'object' && !Array.isArray(value); const hasId = value => isObject(value) && Object.hasOwn(value, 'id'); const validId = value => typeof value === 'string' || (typeof value === 'number' && Number.isFinite(value)); const fail = (id, code, message) => ({ jsonrpc: '2.0', id: id ?? null, error: { code, message } }); const reply = (id, result) => ({ jsonrpc: '2.0', id, result })
const validArguments = (tool, args) => validateSchema(args, tool.inputSchema)
export function createHandler({ sessionToken = process.env.MMSTOPWATCH_CONTROL_PLANE_TOKEN, service } = {}) { service ??= (() => { try { return createService() } catch { const unavailable = async () => ({ ok: false, error: { code: 'NOT_CONFIGURED', message: 'Vault configuration is required' } }); return new Proxy({ capabilities: async () => ({ ok: true, data: { commands: [], unavailable: { all: 'Vault configuration is required' } } }) }, { get: (target, property) => target[property] ?? unavailable }) } })(); let state = 'new'; let closed = false
  const handler = async message => { if (closed) return hasId(message) ? fail(message.id, -32002, 'MCP session is closed') : undefined; if (!isObject(message) || message.jsonrpc !== '2.0' || typeof message.method !== 'string' || (hasId(message) && !validId(message.id))) return hasId(message) ? fail(message.id, -32600, 'Invalid Request') : undefined; if (Object.hasOwn(message, 'params') && !isObject(message.params)) return hasId(message) ? fail(message.id, -32600, 'Invalid Request') : undefined; const id = message.id
    if (message.method === 'notifications/initialized') { if (id !== undefined) return fail(id, -32600, 'Notification must not have an id'); if (state === 'awaiting_initialized') state = 'ready'; return undefined }
    if (message.method === 'initialize') { if (state !== 'new') return id === undefined ? undefined : fail(id, -32600, 'Already initialized'); const p = message.params; if (!p || p.protocolVersion !== PROTOCOL_VERSION || !isObject(p.clientInfo) || !isObject(p.capabilities)) return id === undefined ? undefined : fail(id, -32602, 'Invalid initialize parameters'); state = 'awaiting_initialized'; return id === undefined ? undefined : reply(id, { protocolVersion: PROTOCOL_VERSION, capabilities: { tools: {} }, serverInfo: { name: 'mmstopwatch', version: VERSION } }) }
    if (id === undefined) return undefined; if (state !== 'ready') return fail(id, -32002, 'MCP session is not initialized'); if (message.method === 'ping') return reply(id, {})
    if (message.method === 'tools/list') return reply(id, { tools: tools.map(({ method, ...tool }) => tool) }); if (message.method !== 'tools/call') return fail(id, -32601, 'Method not found'); if (!isObject(message.params)) return fail(id, -32602, 'Invalid tools/call parameters'); const { name, arguments: args = {} } = message.params; const tool = tools.find(item => item.name === name); if (!tool) return fail(id, -32602, 'Unknown tool'); if (!validArguments(tool, args)) return fail(id, -32602, 'Invalid tool arguments'); if (typeof sessionToken !== 'string' || !sessionToken) return reply(id, { isError: true, content: [{ type: 'text', text: JSON.stringify({ ok: false, error: { code: 'AUTH_REQUIRED', message: 'Control-plane token is not configured' } }) }] }); const result = await service[tool.method](args); return reply(id, { isError: !result.ok, content: [{ type: 'text', text: JSON.stringify(result) }], structuredContent: result })
  }
  handler.close = () => { closed = true }; return handler
}
export async function run({ input = stdin, output = stdout, diagnostic = stderr } = {}) { const handler = createHandler(); let closed = false; const close = () => { if (!closed) { closed = true; handler.close(); input.destroy?.() } }; const signal = () => { process.exitCode = 0; close() }; process.once('SIGINT', signal); process.once('SIGTERM', signal); diagnostic.write('mmStopWatch MCP stdio adapter\n'); try { let pending = Buffer.alloc(0); const decoder = new TextDecoder('utf-8', { fatal: true }); for await (const chunk of input) { pending = Buffer.concat([pending, Buffer.from(chunk)]); let index; while ((index = pending.indexOf(10)) >= 0) { const line = pending.subarray(0, index); pending = pending.subarray(index + 1); if (line.length > MAX_FRAME_BYTES) { output.write(`${JSON.stringify(fail(null, -32600, 'Frame exceeds 1 MiB limit'))}\n`); continue } if (!line.toString().trim()) continue; let message; try { message = JSON.parse(decoder.decode(line)) } catch { output.write(`${JSON.stringify(fail(null, -32700, 'Parse error'))}\n`); continue } const response = await handler(message); if (response) output.write(`${JSON.stringify(response)}\n`) } if (pending.length > MAX_FRAME_BYTES) { output.write(`${JSON.stringify(fail(null, -32600, 'Frame exceeds 1 MiB limit'))}\n`); pending = Buffer.alloc(0) } } if (pending.length) { try { const message = JSON.parse(decoder.decode(pending)); const response = await handler(message); if (response) output.write(`${JSON.stringify(response)}\n`) } catch { output.write(`${JSON.stringify(fail(null, -32700, 'Parse error'))}\n`) } } } finally { process.removeListener('SIGINT', signal); process.removeListener('SIGTERM', signal); close() } }
if (import.meta.url === `file://${process.argv[1]}`) run().catch(error => { stderr.write(`MCP transport failure: ${error instanceof Error ? error.message : 'unknown error'}\n`); process.exitCode = 1 })
